### ISSUE TITLE
weapon_updater mismatching weapon type. Unable to retrieve weapon type from Wiki

### ISSUE THREAD

**Issue by g-iori** [Valkam-Git/WFM-Riven-Search#4]
```
Traceback (most recent call last):
  File "D:\Tools\Warframe Deal Finder\deal_finder.py", line 15, in <module>
    user_commands.choose_category()
  File "D:\Tools\Warframe Deal Finder\user_commands.py", line 41, in choose_category
    weapon_updater.get_weapons()
  File "D:\Tools\Warframe Deal Finder\weapon_updater.py", line 84, in get_weapons
    newWeapon["type"] = get_weapon_type(wiki, weapon["name"])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Tools\Warframe Deal Finder\weapon_updater.py", line 34, in get_weapon_type
    return wiki[weapon_name]["Type"]
           ~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'Type'
```

Did the wiki change something?

**Comment by g-iori** [comment]
I managed to fix the issue.

The "get_weapon_type" invocation at line 106 of weapon_updater.py was passing incorrect parameters.

Replaced weapon["Type"] with weapon["name"] and it worked.
